### ISSUE TITLE
Issue in installing Bao extension

### ISSUE THREAD

**Issue by sohail756** [learnedsystems/BaoForPostgreSQL#1]
I am following the tutorial "BAO for PostgreSQL"https://rmarcus.info/bao_docs/tutorial.html. I installed postgresql in archlinux box of Vagrant and loaded the imdb dataset. I tested the dataset with the test case specified in the tutorial and it worked fine. When I tried to install the Bao Extension https://rmarcus.info/bao_docs/tutorial/1_pg_setup.html#install-the-bao-extension, it gave a list of errors and warnings. I tried this setup in Ubuntu OS without using Vagrant but faced with the same problem. The result is listed below:
[vagrant@archlinux BaoForPostgreSQL]$ cd pg_extension
[vagrant@archlinux pg_extension]$ make USE_PGXS=1 install
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fPIC -I. -I./ -I/usr/include/postgresql/server -I/usr/include/postgresql/internal -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2 -c -o main.o main.c
In file included from main.c:10:
bao_planner.h: In function ‘plan_arm’:
bao_planner.h:220:41: warning: passing argument 2 of ‘standard_planner’ makes pointer from integer without a cast [-Wint-conversion]
220 | plan = standard_planner(query_copy, cursorOptions, boundParams);
| ^~~~~~~~~~~~~
| |
| int
In file included from bao_util.h:8,
from main.c:8:
/usr/include/postgresql/server/optimizer/planner.h:41:64: note: expected ‘const char *’ but argument is of type ‘int’
41 | ern PlannedStmt *standard_planner(Query *parse, const char *query_string,
| ~~~~~~~~~~~~^~~~~~~~~~~~

In file included from main.c:10:
bao_planner.h:220:56: warning: passing argument 3 of ‘standard_planner’ makes integer from pointer without a cast [-Wint-conversion]
220 | plan = standard_planner(query_copy, cursorOptions, boundParams);
| ^~~~~~~~~~~
| |
| ParamListInfo {aka struct ParamListInfoData *}
In file included from bao_util.h:8,
from main.c:8:
/usr/include/postgresql/server/optimizer/planner.h:42:15: note: expected ‘int’ but argument is of type ‘ParamListInfo’ {aka ‘struct ParamListInfoData *’}
42 | int cursorOptions,
| ~~~~^~~~~~~~~~~~~
In file included from main.c:10:
bao_planner.h:220:12: error: too few arguments to function ‘standard_planner’
220 | plan = standard_planner(query_copy, cursorOptions, boundParams);
| ^~~~~~~~~~~~~~~~
In file included from bao_util.h:8,
from main.c:8:
/usr/include/postgresql/server/optimizer/planner.h:41:21: note: declared here
41 | extern PlannedStmt *standard_planner(Query *parse, const char *query_string,
| ^~~~~~~~~~~~~~~~
In file included from main.c:10:
bao_planner.h:228:43: warning: passing argument 2 of ‘standard_planner’ makes pointer from integer without a cast [-Wint-conversion]
228 | plan = standard_planner(query_copy, cursorOptions, boundParams);
| ^~~~~~~~~~~~~
| |
| int
bao_planner.h:22:5: note: in definition of macro ‘save_arm_options’
22 | { x }
| ^
In file included from bao_util.h:8,
from main.c:8:
/usr/include/postgresql/server/optimizer/planner.h:41:64: note: expected ‘const char *’ but argument is of type ‘int’
41 | ern PlannedStmt *standard_planner(Query *parse, const char *query_string,
| ~~~~~~~~~~~~^~~~~~~~~~~~

In file included from main.c:10:
bao_planner.h:228:58: warning: passing argument 3 of ‘standard_planner’ makes integer from pointer without a cast [-Wint-conversion]
228 | plan = standard_planner(query_copy, cursorOptions, boundParams);
| ^~~~~~~~~~~
| |
| ParamListInfo {aka struct ParamListInfoData *}
bao_planner.h:22:5: note: in definition of macro ‘save_arm_options’
22 | { x }
| ^
In file included from bao_util.h:8,
from main.c:8:
/usr/include/postgresql/server/optimizer/planner.h:42:15: note: expected ‘int’ but argument is of type ‘ParamListInfo’ {aka ‘struct ParamListInfoData *’}
42 | int cursorOptions,
| ~~~~^~~~~~~~~~~~~
In file included from main.c:10:
bao_planner.h:228:14: error: too few arguments to function ‘standard_planner’
228 | plan = standard_planner(query_copy, cursorOptions, boundParams);
| ^~~~~~~~~~~~~~~~
bao_planner.h:22:5: note: in definition of macro ‘save_arm_options’
22 | { x }
| ^
In file included from bao_util.h:8,
from main.c:8:
/usr/include/postgresql/server/optimizer/planner.h:41:21: note: declared here
41 | extern PlannedStmt *standard_planner(Query *parse, const char query_string,
| ^~~~~~~~~~~~~~~~
main.c: In function ‘_PG_init’:
main.c:61:16: warning: assignment to ‘planner_hook_type’ {aka ‘PlannedStmt * ()(Query *, const char *, int, struct ParamListInfoData )’} from incompatible pointer type ‘PlannedStmt * ()(Query *, int, struct ParamListInfoData *)’ [-Wincompatible-pointer-types]
61 | planner_hook = bao_planner;
| ^
main.c: In function ‘bao_planner’:
main.c:166:37: warning: passing argument 2 of ‘prev_planner_hook’ makes pointer from integer without a cast [-Wint-conversion]
166 | return prev_planner_hook(parse, cursorOptions,
| ^~~~~~~~~~~~~
| |
| int
main.c:166:37: note: expected ‘const char *’ but argument is of type ‘int’
main.c:167:30: warning: passing argument 3 of ‘prev_planner_hook’ makes integer from pointer without a cast [-Wint-conversion]
167 | boundParams);
| ^~~~~~~~~~~
| |
| ParamListInfo {aka struct ParamListInfoData *}
main.c:167:30: note: expected ‘int’ but argument is of type ‘ParamListInfo’ {aka ‘struct ParamListInfoData *’}
main.c:166:12: error: too few arguments to function ‘prev_planner_hook’
166 | return prev_planner_hook(parse, cursorOptions,
| ^~~~~~~~~~~~~~~~~
main.c:175:36: warning: passing argument 2 of ‘standard_planner’ makes pointer from integer without a cast [-Wint-conversion]
175 | return standard_planner(parse, cursorOptions,
| ^~~~~~~~~~~~~
| |
| int
In file included from bao_util.h:8,
from main.c:8:
/usr/include/postgresql/server/optimizer/planner.h:41:64: note: expected ‘const char *’ but argument is of type ‘int’
41 | ern PlannedStmt *standard_planner(Query *parse, const char *query_string,
| ~~~~~~~~~~~~^~~~~~~~~~~~

main.c:176:29: warning: passing argument 3 of ‘standard_planner’ makes integer from pointer without a cast [-Wint-conversion]
176 | boundParams);
| ^~~~~~~~~~~
| |
| ParamListInfo {aka struct ParamListInfoData *}
In file included from bao_util.h:8,
from main.c:8:
/usr/include/postgresql/server/optimizer/planner.h:42:15: note: expected ‘int’ but argument is of type ‘ParamListInfo’ {aka ‘struct ParamListInfoData *’}
42 | int cursorOptions,
| ~~~~^~~~~~~~~~~~~
main.c:175:12: error: too few arguments to function ‘standard_planner’
175 | return standard_planner(parse, cursorOptions,
| ^~~~~~~~~~~~~~~~
In file included from bao_util.h:8,
from main.c:8:
/usr/include/postgresql/server/optimizer/planner.h:41:21: note: declared here
41 | extern PlannedStmt *standard_planner(Query *parse, const char *query_string,
| ^~~~~~~~~~~~~~~~
main.c:187:36: warning: passing argument 2 of ‘standard_planner’ makes pointer from integer without a cast [-Wint-conversion]
187 | return standard_planner(parse, cursorOptions, boundParams);
| ^~~~~~~~~~~~~
| |
| int
In file included from bao_util.h:8,
from main.c:8:
/usr/include/postgresql/server/optimizer/planner.h:41:64: note: expected ‘const char *’ but argument is of type ‘int’
41 | ern PlannedStmt *standard_planner(Query *parse, const char *query_string,
| ~~~~~~~~~~~~^~~~~~~~~~~~

main.c:187:51: warning: passing argument 3 of ‘standard_planner’ makes integer from pointer without a cast [-Wint-conversion]
187 | return standard_planner(parse, cursorOptions, boundParams);
| ^~~~~~~~~~~
| |
| ParamListInfo {aka struct ParamListInfoData *}
In file included from bao_util.h:8,
from main.c:8:
/usr/include/postgresql/server/optimizer/planner.h:42:15: note: expected ‘int’ but argument is of type ‘ParamListInfo’ {aka ‘struct ParamListInfoData *’}
42 | int cursorOptions,
| ~~~~^~~~~~~~~~~~~
main.c:187:12: error: too few arguments to function ‘standard_planner’
187 | return standard_planner(parse, cursorOptions, boundParams);
| ^~~~~~~~~~~~~~~~
In file included from bao_util.h:8,
from main.c:8:
/usr/include/postgresql/server/optimizer/planner.h:41:21: note: declared here
41 | extern PlannedStmt *standard_planner(Query *parse, const char *query_string,
| ^~~~~~~~~~~~~~~~
main.c: In function ‘bao_ExplainOneQuery’:
main.c:318:46: warning: passing argument 2 of ‘planner_hook’ makes pointer from integer without a cast [-Wint-conversion]
318 | plan = (planner_hook ? planner_hook(query, cursorOptions, params)
| ^~~~~~~~~~~~~
| |
| int
main.c:318:46: note: expected ‘const char *’ but argument is of type ‘int’
main.c:318:61: warning: passing argument 3 of ‘planner_hook’ makes integer from pointer without a cast [-Wint-conversion]
318 | plan = (planner_hook ? planner_hook(query, cursorOptions, params)
| ^~~~~~
| |
| ParamListInfo {aka struct ParamListInfoData *}
main.c:318:61: note: expected ‘int’ but argument is of type ‘ParamListInfo’ {aka ‘struct ParamListInfoData *’}
main.c:318:26: error: too few arguments to function ‘planner_hook’
318 | plan = (planner_hook ? planner_hook(query, cursorOptions, params)
| ^~~~~~~~~~~~
main.c:319:37: warning: passing argument 2 of ‘standard_planner’ makes pointer from integer without a cast [-Wint-conversion]
319 | : standard_planner(query, cursorOptions, params));
| ^~~~~~~~~~~~~
| |
| int
In file included from bao_util.h:8,
from main.c:8:
/usr/include/postgresql/server/optimizer/planner.h:41:64: note: expected ‘const char *’ but argument is of type ‘int’
41 | ern PlannedStmt *standard_planner(Query *parse, const char *query_string,
| ~~~~~~~~~~~~^~~~~~~~~~~~

main.c:319:52: warning: passing argument 3 of ‘standard_planner’ makes integer from pointer without a cast [-Wint-conversion]
319 | : standard_planner(query, cursorOptions, params));
| ^~~~~~
| |
| ParamListInfo {aka struct ParamListInfoData *}
In file included from bao_util.h:8,
from main.c:8:
/usr/include/postgresql/server/optimizer/planner.h:42:15: note: expected ‘int’ but argument is of type ‘ParamListInfo’ {aka ‘struct ParamListInfoData *’}
42 | int cursorOptions,
| ~~~~^~~~~~~~~~~~~
main.c:319:13: error: too few arguments to function ‘standard_planner’
319 | : standard_planner(query, cursorOptions, params));
| ^~~~~~~~~~~~~~~~
In file included from bao_util.h:8,
from main.c:8:
/usr/include/postgresql/server/optimizer/planner.h:41:21: note: declared here
41 | extern PlannedStmt *standard_planner(Query *parse, const char *query_string,
| ^~~~~~~~~~~~~~~~
main.c:325:5: error: too few arguments to function ‘ExplainOnePlan’
325 | ExplainOnePlan(plan, into, es, queryString,
| ^~~~~~~~~~~~~~
In file included from main.c:17:
/usr/include/postgresql/server/commands/explain.h:90:13: note: declared here
90 | extern void ExplainOnePlan(PlannedStmt *plannedstmt, IntoClause *into,
| ^~~~~~~~~~~~~~
main.c:399:3: error: too few arguments to function ‘ExplainOnePlan’
399 | ExplainOnePlan(plan, into, es, queryString,
| ^~~~~~~~~~~~~~
In file included from main.c:17:
/usr/include/postgresql/server/commands/explain.h:90:13: note: declared here
90 | extern void ExplainOnePlan(PlannedStmt *plannedstmt, IntoClause *into,
| ^~~~~~~~~~~~~~
make: *** [: main.o] Error 1

**Comment by Issam28** [comment]
I'm facing the same problem when I tried to install Bao extension on Ubuntu 18.04.1.
Hope devs look into this.

**Comment by Issam28** [comment]
@sohail756 I have found a solution. Downgrade Postgresql to version 12.

**Comment by sohail756** [comment]
> @sohail756 I have found a solution. Downgrade Postgresql to version 12.

Thanks buddy, I will also try it.

**Comment by sohail756** [comment]
> @sohail756 I have found a solution. Downgrade Postgresql to version 12.

I tried your solution but unfortunately, it didn't work for me.
I completely uninstalled postgresql 13 from my system(Ubuntu 20.04). I then installed postgresql version "12.6", loaded the imdb dataset but when I ran this command (sudo apt-get install postgresql-server-dev-all postgresql-common) to install the required packages. My postgresql automatically updated to version 13. I again uninstalled postgresql and repeated the same process. This time I didn't run the above command and manually loaded the required libraries but when I ran the command to install the bao extension it gave me those errors which were there initially.

**Comment by zhaoyuehrb** [comment]
@sohail756 Exact same problem here. May I ask if you had any updates?

**Comment by sohail756** [comment]
@zhaoyuehrb Install postgresql 12.6, load the imdb dataset but when you run this command "sudo apt-get install postgresql-server-dev-all postgresql-common", change "all" to "postgres-server-dev-12". It will work then.

**Comment by zhaoyuehrb** [comment]
@sohail756 It works! Thank you!

**Comment by RyanMarcus** [comment]
Hi everyone,

Very sorry for the trouble -- indeed, Bao currently requires PG12. I will work on upgrading to PG13 soon!

Thanks,

Ryan
