### ISSUE TITLE
Is there multi-armed bandit and Thompson sampling in this implementation?

### ISSUE THREAD

**Issue by LumingSun** [learnedsystems/BaoForPostgreSQL#8]
Hi @RyanMarcus , I read the code and found 
https://github.com/learnedsystems/BaoForPostgreSQL/blob/28142c74903cbf0873b614b3b4f3bc49c5f84a1f/bao_server/main.py#L37
So in this implementation, the selected plan is right the plan with minimum estimated cost rather than the plan using Thompson sampling?

**Comment by RyanMarcus** [comment]
The model used in the linked line is trained on a  bootstrap of the training data (or at least it should be), so it's a model with parameters sampled from `P(θ|E)`. 

Sorry for the delay, just got back from break.
